---
name: ci

on:
  push:
    branches:
    - '**'
    tags:
    - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Import Secrets
      id: secrets # important to refer to it in later steps
      uses: hashicorp/vault-action@v2.5.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false # we rely on step outputs, no need for environment variables
        secrets: |
          secret/data/products/infra/ci/common BUILDER_INT_TO_K8S_INTERNAL;
    - id: build_gcr
      uses: camunda/infra-global-github-actions/build-docker-image@main
      with:
        registry_host: gcr.io
        registry_username: _json_key
        registry_password: ${{ steps.secrets.outputs.BUILDER_INT_TO_K8S_INTERNAL }}
        image_name: camunda-internal/infra-logrotate
